#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLLaoDong
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLLaoDong")]
	public partial class qlLaoDongDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblCongTrinh(tblCongTrinh instance);
    partial void UpdatetblCongTrinh(tblCongTrinh instance);
    partial void DeletetblCongTrinh(tblCongTrinh instance);
    partial void InserttblNhanVien(tblNhanVien instance);
    partial void UpdatetblNhanVien(tblNhanVien instance);
    partial void DeletetblNhanVien(tblNhanVien instance);
    partial void InserttblPhongBan(tblPhongBan instance);
    partial void UpdatetblPhongBan(tblPhongBan instance);
    partial void DeletetblPhongBan(tblPhongBan instance);
    #endregion
		
		public qlLaoDongDataContext() : 
				base(global::QLLaoDong.Properties.Settings.Default.QLLaoDongConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public qlLaoDongDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlLaoDongDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlLaoDongDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlLaoDongDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblCongTrinh> tblCongTrinhs
		{
			get
			{
				return this.GetTable<tblCongTrinh>();
			}
		}
		
		public System.Data.Linq.Table<tblNhanVien> tblNhanViens
		{
			get
			{
				return this.GetTable<tblNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tblPhongBan> tblPhongBans
		{
			get
			{
				return this.GetTable<tblPhongBan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCongTrinh")]
	public partial class tblCongTrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCT;
		
		private string _TenCT;
		
		private string _DiaDiemCT;
		
		private System.Nullable<System.DateTime> _Ngaycapgiayphep;
		
		private System.Nullable<System.DateTime> _Ngaykhoicong;
		
		private System.Nullable<System.DateTime> _NgayhoanthanhDK;
		
		private EntitySet<tblNhanVien> _tblNhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTChanging(string value);
    partial void OnMaCTChanged();
    partial void OnTenCTChanging(string value);
    partial void OnTenCTChanged();
    partial void OnDiaDiemCTChanging(string value);
    partial void OnDiaDiemCTChanged();
    partial void OnNgaycapgiayphepChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaycapgiayphepChanged();
    partial void OnNgaykhoicongChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaykhoicongChanged();
    partial void OnNgayhoanthanhDKChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayhoanthanhDKChanged();
    #endregion
		
		public tblCongTrinh()
		{
			this._tblNhanViens = new EntitySet<tblNhanVien>(new Action<tblNhanVien>(this.attach_tblNhanViens), new Action<tblNhanVien>(this.detach_tblNhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					this.OnMaCTChanging(value);
					this.SendPropertyChanging();
					this._MaCT = value;
					this.SendPropertyChanged("MaCT");
					this.OnMaCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCT", DbType="NVarChar(50)")]
		public string TenCT
		{
			get
			{
				return this._TenCT;
			}
			set
			{
				if ((this._TenCT != value))
				{
					this.OnTenCTChanging(value);
					this.SendPropertyChanging();
					this._TenCT = value;
					this.SendPropertyChanged("TenCT");
					this.OnTenCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiemCT", DbType="NVarChar(50)")]
		public string DiaDiemCT
		{
			get
			{
				return this._DiaDiemCT;
			}
			set
			{
				if ((this._DiaDiemCT != value))
				{
					this.OnDiaDiemCTChanging(value);
					this.SendPropertyChanging();
					this._DiaDiemCT = value;
					this.SendPropertyChanged("DiaDiemCT");
					this.OnDiaDiemCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaycapgiayphep", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaycapgiayphep
		{
			get
			{
				return this._Ngaycapgiayphep;
			}
			set
			{
				if ((this._Ngaycapgiayphep != value))
				{
					this.OnNgaycapgiayphepChanging(value);
					this.SendPropertyChanging();
					this._Ngaycapgiayphep = value;
					this.SendPropertyChanged("Ngaycapgiayphep");
					this.OnNgaycapgiayphepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaykhoicong", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaykhoicong
		{
			get
			{
				return this._Ngaykhoicong;
			}
			set
			{
				if ((this._Ngaykhoicong != value))
				{
					this.OnNgaykhoicongChanging(value);
					this.SendPropertyChanging();
					this._Ngaykhoicong = value;
					this.SendPropertyChanged("Ngaykhoicong");
					this.OnNgaykhoicongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayhoanthanhDK", DbType="Date")]
		public System.Nullable<System.DateTime> NgayhoanthanhDK
		{
			get
			{
				return this._NgayhoanthanhDK;
			}
			set
			{
				if ((this._NgayhoanthanhDK != value))
				{
					this.OnNgayhoanthanhDKChanging(value);
					this.SendPropertyChanging();
					this._NgayhoanthanhDK = value;
					this.SendPropertyChanged("NgayhoanthanhDK");
					this.OnNgayhoanthanhDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCongTrinh_tblNhanVien", Storage="_tblNhanViens", ThisKey="MaCT", OtherKey="MaCT")]
		public EntitySet<tblNhanVien> tblNhanViens
		{
			get
			{
				return this._tblNhanViens;
			}
			set
			{
				this._tblNhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblNhanViens(tblNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tblCongTrinh = this;
		}
		
		private void detach_tblNhanViens(tblNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tblCongTrinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhanVien")]
	public partial class tblNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _Hoten;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _Gioitinh;
		
		private string _Lienhe;
		
		private string _MaCT;
		
		private string _MaPB;
		
		private EntityRef<tblCongTrinh> _tblCongTrinh;
		
		private EntityRef<tblPhongBan> _tblPhongBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnLienheChanging(string value);
    partial void OnLienheChanged();
    partial void OnMaCTChanging(string value);
    partial void OnMaCTChanged();
    partial void OnMaPBChanging(string value);
    partial void OnMaPBChanged();
    #endregion
		
		public tblNhanVien()
		{
			this._tblCongTrinh = default(EntityRef<tblCongTrinh>);
			this._tblPhongBan = default(EntityRef<tblPhongBan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(50)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lienhe", DbType="NVarChar(50)")]
		public string Lienhe
		{
			get
			{
				return this._Lienhe;
			}
			set
			{
				if ((this._Lienhe != value))
				{
					this.OnLienheChanging(value);
					this.SendPropertyChanging();
					this._Lienhe = value;
					this.SendPropertyChanged("Lienhe");
					this.OnLienheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", DbType="NVarChar(50)")]
		public string MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					if (this._tblCongTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCTChanging(value);
					this.SendPropertyChanging();
					this._MaCT = value;
					this.SendPropertyChanged("MaCT");
					this.OnMaCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPB", DbType="NVarChar(50)")]
		public string MaPB
		{
			get
			{
				return this._MaPB;
			}
			set
			{
				if ((this._MaPB != value))
				{
					if (this._tblPhongBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPBChanging(value);
					this.SendPropertyChanging();
					this._MaPB = value;
					this.SendPropertyChanged("MaPB");
					this.OnMaPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCongTrinh_tblNhanVien", Storage="_tblCongTrinh", ThisKey="MaCT", OtherKey="MaCT", IsForeignKey=true)]
		public tblCongTrinh tblCongTrinh
		{
			get
			{
				return this._tblCongTrinh.Entity;
			}
			set
			{
				tblCongTrinh previousValue = this._tblCongTrinh.Entity;
				if (((previousValue != value) 
							|| (this._tblCongTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCongTrinh.Entity = null;
						previousValue.tblNhanViens.Remove(this);
					}
					this._tblCongTrinh.Entity = value;
					if ((value != null))
					{
						value.tblNhanViens.Add(this);
						this._MaCT = value.MaCT;
					}
					else
					{
						this._MaCT = default(string);
					}
					this.SendPropertyChanged("tblCongTrinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhongBan_tblNhanVien", Storage="_tblPhongBan", ThisKey="MaPB", OtherKey="MaPB", IsForeignKey=true)]
		public tblPhongBan tblPhongBan
		{
			get
			{
				return this._tblPhongBan.Entity;
			}
			set
			{
				tblPhongBan previousValue = this._tblPhongBan.Entity;
				if (((previousValue != value) 
							|| (this._tblPhongBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPhongBan.Entity = null;
						previousValue.tblNhanViens.Remove(this);
					}
					this._tblPhongBan.Entity = value;
					if ((value != null))
					{
						value.tblNhanViens.Add(this);
						this._MaPB = value.MaPB;
					}
					else
					{
						this._MaPB = default(string);
					}
					this.SendPropertyChanged("tblPhongBan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhongBan")]
	public partial class tblPhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPB;
		
		private string _TenPB;
		
		private EntitySet<tblNhanVien> _tblNhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPBChanging(string value);
    partial void OnMaPBChanged();
    partial void OnTenPBChanging(string value);
    partial void OnTenPBChanged();
    #endregion
		
		public tblPhongBan()
		{
			this._tblNhanViens = new EntitySet<tblNhanVien>(new Action<tblNhanVien>(this.attach_tblNhanViens), new Action<tblNhanVien>(this.detach_tblNhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPB", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPB
		{
			get
			{
				return this._MaPB;
			}
			set
			{
				if ((this._MaPB != value))
				{
					this.OnMaPBChanging(value);
					this.SendPropertyChanging();
					this._MaPB = value;
					this.SendPropertyChanged("MaPB");
					this.OnMaPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPB", DbType="NVarChar(50)")]
		public string TenPB
		{
			get
			{
				return this._TenPB;
			}
			set
			{
				if ((this._TenPB != value))
				{
					this.OnTenPBChanging(value);
					this.SendPropertyChanging();
					this._TenPB = value;
					this.SendPropertyChanged("TenPB");
					this.OnTenPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhongBan_tblNhanVien", Storage="_tblNhanViens", ThisKey="MaPB", OtherKey="MaPB")]
		public EntitySet<tblNhanVien> tblNhanViens
		{
			get
			{
				return this._tblNhanViens;
			}
			set
			{
				this._tblNhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblNhanViens(tblNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tblPhongBan = this;
		}
		
		private void detach_tblNhanViens(tblNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tblPhongBan = null;
		}
	}
}
#pragma warning restore 1591
