<?xml version="1.0" encoding="utf-8"?><Database Name="QLLaoDong" Class="qlLaoDongDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-B4NT82SO\SQLEXPRESS;Initial Catalog=QLLaoDong;Integrated Security=True" SettingsObjectName="QLLaoDong.Properties.Settings" SettingsPropertyName="QLLaoDongConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblCongTrinh" Member="tblCongTrinhs">
    <Type Name="tblCongTrinh">
      <Column Name="MaCT" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaDiemCT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaycapgiayphep" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Ngaykhoicong" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayhoanthanhDK" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="tblCongTrinh_tblNhanVien" Member="tblNhanViens" ThisKey="MaCT" OtherKey="MaCT" Type="tblNhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.tblNhanVien" Member="tblNhanViens">
    <Type Name="tblNhanVien">
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Hoten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gioitinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lienhe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaCT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaPB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblCongTrinh_tblNhanVien" Member="tblCongTrinh" ThisKey="MaCT" OtherKey="MaCT" Type="tblCongTrinh" IsForeignKey="true" />
      <Association Name="tblPhongBan_tblNhanVien" Member="tblPhongBan" ThisKey="MaPB" OtherKey="MaPB" Type="tblPhongBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPhongBan" Member="tblPhongBans">
    <Type Name="tblPhongBan">
      <Column Name="MaPB" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblPhongBan_tblNhanVien" Member="tblNhanViens" ThisKey="MaPB" OtherKey="MaPB" Type="tblNhanVien" />
    </Type>
  </Table>
</Database>